force-app/main/default/objects/compliancequest__SQX_Nonconformance__c/compliancequest__SQX_Nonconformance__c.object-meta.xml
<CustomObject>
    <description>This entity is responsible for storing information specific to Non-conformance. It will be used to record information such as type of NC, its priority, related department and so forth. Non-conformance can be defined as any abnormality(deviation from the standard/specification) seen in a process or product in an organization.</description>
    <label>Nonconformance</label>
    <nameField>
        <displayFormat>NC-{000000}</displayFormat>
        <label>NC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nonconformance</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/compliancequest__SQX_Nonconformance__c/fields/Related_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_to_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Nonconformance</relationshipLabel>
    <relationshipName>Nonconformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Testsolvevaibhav.cls
@isTest
public class Testsolvevaibhav {
    public static User u;
    public static PermissionSet ps;
    @testSetup
    public static void setup() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        system.debug(p);
        
        ps = [SELECT Id FROM PermissionSet WHERE Name='CQ_Admin_Extended_Permissions'];
        system.debug(ps);
        
        u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                     LocaleSidKey='en_US', ProfileId = p.Id,
                     TimeZoneSidKey='America/Los_Angeles', UserName='testpermissionsetuserAstreait@testorg.com');
        insert u;
        system.debug('user' + u);
        system.debug(' system.debug(UserInfo.getUserId()) '+UserInfo.getUserId());
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = u.Id,
            PermissionSetId = ps.Id
        );
        insert psa; 
    }
    
    @isTest
    public static void testsolveInsertion(){
        User u = [select Id,Name from User where UserName='testpermissionsetuserAstreait@testorg.com'];
        System.runAs(u) {
            Case newCase = new Case();
            newCase.Subject = 'Example Case Subject';
            newCase.Description = 'Example Case Description';
            newCase.Status = 'New'; 
            newCase.Origin = 'Web'; 
            newCase.Type='Problem';
            insert newCase;
            
            
            
            List<compliancequest__SQX_Nonconformance__c> creatednon = [SELECT Id FROM compliancequest__SQX_Nonconformance__c WHERE Related_to_Case__c = :newCase.Id];
            System.assertEquals(1, creatednon.size());
            
        }
        
    }
        @isTest
        public static void testsolveFalied() {
            
            User u = [select Id,Name from User where UserName='testpermissionsetuserAstreait@testorg.com'];
            System.runAs(u) {
                Case newCase = new Case();
                newCase.Subject = 'Example Case Subject';
                newCase.Description = 'Example Case Description';
                newCase.Status = 'New'; 
                newCase.Origin = 'Web'; 
                newCase.Type='Question';
                insert newCase;
                
                
                
                List<compliancequest__SQX_Nonconformance__c> creatednon = [SELECT Id FROM compliancequest__SQX_Nonconformance__c WHERE Related_to_Case__c = :newCase.Id];
                System.assertEquals(0, creatednon.size());
                
                
            }
        }
            
            @isTest
            public static void testsolveUpdate() {
                
                User u = [select Id,Name from User where UserName='testpermissionsetuserAstreait@testorg.com'];
                System.runAs(u) {
                    Case newCase = new Case();
                    newCase.Subject = 'Example Case Subject';
                    newCase.Description = 'Example Case Description';
                    newCase.Status = 'New'; 
                    newCase.Origin = 'Web'; 
                    newCase.Type='Question';
                    
                    insert newCase;
                    
                    
                    
                    List<compliancequest__SQX_Nonconformance__c> creatednon1 = [SELECT Id FROM compliancequest__SQX_Nonconformance__c WHERE Related_to_Case__c = :newCase.Id];
                    System.assertEquals(0, creatednon1.size());
                    newCase.Type = 'Problem';
                    update newcase;
                    
                    List<compliancequest__SQX_Nonconformance__c> creatednon = [SELECT Id FROM compliancequest__SQX_Nonconformance__c WHERE Related_to_Case__c = :newCase.Id];
                    System.assertEquals(1, creatednon.size());
                    
                }  
                }
            }